- name: test my new module
  hosts: localhost
  tasks:
  - name: run the new module
    custom_module_nogfi:
      prefix: '1.1.1.0/24'
      ip_offset: 5
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'